name: Terraform CD

on:
 workflow_dispatch:
  inputs:
    environment:
     description: 'Environment to run tf apply on'
     required: true
     default: "dev"
     type: choice
     options:
     ##these options here can be used to load different blocks of yaml for different steps
     - dev
     - staging
     - prod

jobs:
 terraform-cd:
  runs-on: ubuntu-latest

  steps:
  ##setup
  - name: Checkout repository
    uses: actions/checkout@v2


  - name: Set up Terraform
    uses: hashicorp/setup-terraform@v1


  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     aws-region: ${{ vars.REGION }} # or hardcode us-east-1
  ##CD
  - name: Initialize Terraform
    run: terraform init
     
  - name: Terraform Plan
    run: terraform plan

  - name: Terraform Apply
    run: terraform apply --auto-approve
